"""Initial migration

迁移 ID: b3a3a7de2c5e
父迁移:
创建时间: 2025-06-19 04:05:55.471041

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "b3a3a7de2c5e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chat_time")
    op.drop_table("BilibiliAccount")
    op.drop_table("chat_time_total")
    with op.batch_alter_table("cave_models", schema=None) as batch_op:
        batch_op.alter_column(
            "anonymous",
            existing_type=mysql.TINYINT(display_width=1),
            nullable=False,
            existing_server_default=sa.text("0"),
        )
        batch_op.drop_table_comment(
            existing_comment="Model representing the cave_models table in the database."
        )

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cave_models", schema=None) as batch_op:
        batch_op.create_table_comment(
            "Model representing the cave_models table in the database.",
            existing_comment=None,
        )
        batch_op.alter_column(
            "anonymous",
            existing_type=mysql.TINYINT(display_width=1),
            nullable=True,
            existing_server_default=sa.text("0"),
        )

    op.create_table(
        "chat_time_total",
        sa.Column(
            "group_id",
            mysql.BIGINT(display_width=20),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "user_time_map",
            mysql.LONGTEXT(charset="utf8mb4", collation="utf8mb4_bin"),
            nullable=False,
        ),
        sa.Column(
            "user_message_map",
            mysql.LONGTEXT(charset="utf8mb4", collation="utf8mb4_bin"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("group_id"),
        mysql_collate="utf8mb4_uca1400_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "BilibiliAccount",
        sa.Column(
            "id",
            mysql.INTEGER(display_width=10, unsigned=True),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("csrf", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("refresh_token", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("SESSDATA", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("DedeUserID", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("DedeUserID__ckMd5", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("bili_ticket_expires", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("bili_ticket", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("bmg_af_switch", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("FEED_LIVE_VERSION", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("browser_resolution", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("header_theme_version", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("home_feed_column", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("bmg_src_def_domain", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("enable_web_push", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("_uuid", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("i-wanna-go-back", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("b_lsid", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("buvid3", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("b_ut", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("buvid_fp", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("b_nut", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("buvid4", mysql.VARCHAR(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_general_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "chat_time",
        sa.Column(
            "group_id",
            mysql.BIGINT(display_width=20),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "timestamp_map",
            mysql.LONGTEXT(charset="utf8mb4", collation="utf8mb4_bin"),
            nullable=False,
        ),
        sa.Column(
            "today_time_map",
            mysql.LONGTEXT(charset="utf8mb4", collation="utf8mb4_bin"),
            nullable=False,
        ),
        sa.Column(
            "today_message_map",
            mysql.LONGTEXT(charset="utf8mb4", collation="utf8mb4_bin"),
            nullable=False,
        ),
        sa.Column(
            "today_remind_time",
            mysql.LONGTEXT(charset="utf8mb4", collation="utf8mb4_bin"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("group_id"),
        mysql_collate="utf8mb4_uca1400_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
