name: Report Test Coverage

on: [pull_request, push]

jobs:
  report_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Report test coverage to DeepSource
        uses: deepsourcelabs/test-coverage-action@master
        with:
          key: python
          coverage-file: coverage.xml
          dsn: ${{ secrets.DEEPSOURCE_DSN }}
          fail-ci-on-error: true  # Optional: Set to true if you want the CI build to fail on error
